### ISSUE TITLE
Иногда не срабатывает автокоммит файла `index.11tydata.json`

### ISSUE THREAD

**Issue by monochromer** [doka-guide/content#1177]
Иногда не срабатывает автокоммит файла `index.11tydata.json`

Например, [здесь видно](https://github.com/doka-guide/content/runs/3106107086), что файл создался, но не был отправлен из-за ошибки:
```
! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 734d4b808503e6d1875efdf47c7f1ec9fb0dbd37 but expected ca497939dfa2ef69a41a72beae566439b222762b)
error: failed to push some refs to 'https://github.com/doka-guide/content'
```

**Comment by pepelsbey** [comment]
Может быть мы можем при сборке в шаблоне или в функции сделать обработку так, чтобы сборка не падала?

**Comment by monochromer** [comment]
Можно, но здесь проблема на уровне github-action - он не смог закоммитить созданный файл `index.11tydata.json`

**Comment by monochromer** [comment]
Как полагаю, ошибка возникает из-за параллельного выполнения _github actions_. В одном action произошел коммит, в другом - происходит merge conflict.

Просить мержить последовательно, дожидаясь полного окончания всех action, - явно не подходит. 

Можно посмотреть в сторону [concurrency](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) (или [сторонний action](https://github.com/byu-oit/github-action-disallow-concurrent-runs)). 

Ну и самый простой вариант - выполнять action внутри _pull request_. Тогда никаких параллельных коммитов не будет. Плюс и одновременно минус - в истории не будет автокоммитов с обновлениями полей, так как используется squash-стратегия.

**Comment by monochromer** [comment]
Кажется, вариант с конкурентностью работает:
```yaml
concurrency:
  group: Update Dates
```
И правка для коммита:
```yaml
- name: git commit
  run: |
   git add ./**/index.11tydata.json
   git commit -m "Правит поля updatedAt и createdAt"

- name: push changes
  run: |
   git pull --rebase
   git push origin main
```
