### ISSUE TITLE
Нет одного примера свойства

### ISSUE THREAD

**Issue by mitorun** [doka-guide/content#2009]
На странице https://doka.guide/css/color/ неполные примеры кода свойств:

Значение HSL в новом синтаксисе hsl для сплошных и для полупрозрачных:
```css
.element {
  color: hsl(30 100% 50% / 0.6);
  color: hsl(30 100% 50% / 60%);
}
```
По логике там должно быть:
```css
.element {
  color: hsl(30 100% 50%);
  color: hsl(30 100% 50% / 0.6);
  color: hsl(30 100% 50% / 60%);
}
```
А в примерах выше вроде бы еще должны быть варианты с процентами, например color: hsla(30, 100%, 50%, 60%);
