### ISSUE TITLE
Улучшения в руководство по созданию демок (demos)

### ISSUE THREAD

**Issue by Mitorun** [doka-guide/content#2303]
## Создание демок

В руководство по созданию демок:
https://github.com/doka-guide/content/blob/main/docs/demos.md
и https://github.com/doka-guide/content/blob/main/docs/examples/doka.md
стоит добавить рекомендации по размерам элемента в демке, цветам, адаптивности: 
- Ширину элемента (например я использовал 310х310px чтобы элемент не обрезался на смартфонах с шириной экрана от 350px, поля примерно по 20px). 
- Высоту элемента (например 310px).
- Соотношение сторон (квадратные элементы предпочтительней прямоугольных, на разных экранах они выглядят норм).
- Высоту `iframe` (мне показались удобными поля по 40px, следовательно высота всего ифрейма 310+40+40=390px).
- Цвет фона. Порекомендовать один или несколько базовых цветов, например `background-color: #18191c;`.
- Можно указать что демки будут сжиматься на смартфонах до (~300-320px), поэтому свои демки надо тестировать на сжатие. И при необходимости добавлять резиновости или уменьшать медиазапросами, чтобы демки в принципе можно было увидеть на узких экранах.

Так постепенно выработать более универсальные правила по демкам и иллюстрациям, чтобы все статьи выглядели в одном стиле. 

Можно указать рекомендуемые базовые стили для демок, например:

```css
html {
  display: grid;
  place-items: center;
  height: 100%;
}
body {
  background-color: #18191c;
}
.element {
  width: 300px;
  height: 300px;
}
```

Добавить описание о том как делать демки в раздел "На практике" (также как и в статье? куда размещать, как вставлять?).

Еще думаю будет хорошо написать в руководстве, что примеры оформления демок (и вообще оформление статей в .md) можно подсмотреть в файлах доки (`content/css/[свойства]`).

UPD. Код демок потом не форматируется и не минифицируется? Если так, то об этом нужно написать в руководстве. Комментарии тогда там можно оставлять. И привести пример как стоит оформлять CSS с длинными свойствами (Вадим говорит что так стоит оформлять и в статье и в демке):

```css
div {
  background:
    radial-gradient(
      yellow 5%,
      gold 31% 32%,
      transparent 32.5% 50%,
      lightskyblue 70%
    ),
    repeating-conic-gradient(
      yellow 0% 1%,
      transparent 4% 6%,
      yellow 9% 10%
    );
}
```
