### ISSUE TITLE
Рецепт с горизонтальным скроллом и тенями на телефоне.

### ISSUE THREAD

**Issue by punkmachine** [doka-guide/content#4299]
### Тема

Написать рецепт горизонтального скролла на телефоне, в котором будет работать логика того, что при клике на элемент. к нему будет идти скролл. Также, самое сложное, что было для меня в этой задаче, справа и слева должны появляться тени. 

### Зачем

Недавно у меня была таска рабочая с таким скроллом. Были затруднения, с которыми помогла Алёна Батицкая в чате. Могу перенести код, который написал с этим скроллом сюда и описать. Думаю будет полезно.

### Кто напишет материал

- [X] Я сам напишу этот материал

**Comment by punkmachine** [comment]
Код мной был написан на вью 2, могу перенести на ванильный JS.

mixin:
```js
export default {
  data() {
    return {
      visibleShadowRight: true,
      visibleShadowLeft: false,
    };
  },
  destroyed() {
    this.removeListenerScroll();
  },
  methods: {
    addListenerScroll() {
      this.$nextTick(() => {
        this.$refs.container.addEventListener('touchmove', this.onScrollContainer);
      });
    },
    removeListenerScroll() {
      if (this.$refs.container) {
        this.$refs.container.removeEventListener('touchmove', this.onScrollContainer);
      }
    },
    onScrollContainer() {
      const { scrollLeft } = this.$refs.container;

      this.visibleShadowRight = scrollLeft <= 0;
      this.visibleShadowLeft = scrollLeft > 0;
    },
  }
};
```

Стили:
```scss
.scroll-shadow {
  z-index: 2;
  width: calc(100% + 32px);
  position: absolute;
  top: 0;
  left: -16px;
  transition: 0.4s all;
  pointer-events: none;

  &--right {
    background: linear-gradient(90deg, rgba(255, 255, 255, 0) 74.65%,
      rgba(255, 255, 255, 0.6) 100%);
  }

  &--left {
    background: linear-gradient(270deg,
      rgba(255, 255, 255, 0) 76.32%, rgba(255, 255, 255, 0.6) 100%);
  }

  &--hide {
    opacity: 0;
  }
}
```

Клик по элементу:
```js
onClick(card) {
        const container = document.querySelector(`[data-saved-card="${card.id}"]`);
        container.scrollIntoView({
          behavior: 'smooth',
          block: 'center',
          inline: 'center',
        });
        
        /* other logic */
      },
```

Разметка:
```html
<div>
      <div ref="container">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
    <div
      class="saved-addresses__shadow scroll-shadow scroll-shadow--left"
      :class="{
        'scroll-shadow__shadow--hide': !visibleShadowRight
      }"
    ></div>
    <div
      class="saved-addresses__shadow scroll-shadow scroll-shadow--right"
      :class="{
        'scroll-shadow__shadow--hide': !visibleShadowLeft
      }"
    ></div>
</div>
```
