### ISSUE TITLE
Не хватает информации о номерах грид-линий

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/content#4408]
### Тема

Не хватает информации о том, как и почему именно такие номера присваиваются грид-линиям. Как пользоваться отрицательными значениями? Почему иногда отрицательных значений меньше, чем положительных?

### Зачем

Во время работы над #4249, я часто путался и не понимал, почему у конкретной грид-линии то или иное значение. Пришлось попробовать самому, всё сломать, починить и опять сломать, чтобы понять что к чему. Например:

```css
.container {
  display: grid;
  grid-template-rows: 50px 150px;
  grid-template-columns: auto;
  grid-auto-rows: 15px;
  gap: 10px;
}
```

![image](https://user-images.githubusercontent.com/91747573/232828624-df511778-5516-4c8e-9d21-e7d8dedcca22.png)

Почему горизонтальный `-1` не в самом конце? Куда делся вертикальный `-2`? В Доке не хватает ответов на эти вопросы
X_X

### Кто напишет материал

- [ ] Я сам напишу этот материал
