### ISSUE TITLE
Добавить baseline в документацию

### ISSUE THREAD

**Issue by fpetrakov** [doka-guide/content#5019]
Описать, как добавлять baseline в свою статью, шаги, пример

**Comment by vitya-ne** [comment]
дока отображает baseline без указания версий:
![изображение](https://github.com/doka-guide/content/assets/9317613/3f91bb2f-042e-4aba-96cb-5bc508a4fab1)

я добавил конфигурацию `baseline` в yaml-шапку доки, согласно [frontmatter.json](https://github.com/doka-guide/content/blob/main/.github/frontmatter.json) после description:
```
baseline:
  - group: array-at
    features:
      - javascript.builtins.Array.at
```
в  [web-platform-dx/web-features](https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/array-at.yml) есть файл `array-at.yml` с features:
```
compat_features:
  - javascript.builtins.Array.at
```
в чем может быть проблема ?
