### ISSUE TITLE
Разбраться, что происходит в демке includes

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#777]
Выглядит как-то дико сложно и кажется здесь нужен просто `::placeholder`, особенно для кроссбраузерности.

```css
.article__code .input:-internal-autofill-selected {
  -webkit-box-shadow: inset 0 0 0 100px #18191c;
  -webkit-text-fill-color: #ffffff;
  caret-color: #ffffff;
}
```
