### ISSUE TITLE
Убрать из  MD-файлов пустые поля

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#784]
Как сейчас:

```yml
title: ":active"
name: active
author: ABatickaya
co-authors:
designers:
contributors:
```

Можно лучше:

```yml
title: ":active"
name: active
author: ABatickaya
```

Это позволяет проверять наличие полей более просто `{% if designers %}`, а сейчас приходится проверять длину поля, а не его наличие. Ну и вообще кажется так становится чище: нет информации — нет поля, есть информация — добавляем.
