### ISSUE TITLE
Вынести лонгрид из кода в текст (nth-of-type)

### ISSUE THREAD

**Issue by pepelsbey** [doka-guide/content#785]
Аналогично в демке. А то неудобно читать:

```css
/* следующий пункт не имеет класса, всё, что мы о нём «знаем» — что он
  третий <li> по порядку */
li:nth-of-type(3) {
  color: green;
}

/* 2 и 4 пункт с классом .list__item имеет синий цвет, т. е. каждый чётный */
.list__item:nth-of-type(2n) {
  /* нечётные элементы записываются как 2n+1 */
  color: blue;
}

/* первый .list__item в списке */
.list__item:first-of-type, /* но этот селектор не сработает, потому что
                              класс .list__item принадлежит к элементу <li>,
                              а у li:first-of-type не указан класс */
/* но это так же и второй <li>, если использовать только тег как селектор
  независимо от того, будет у li указан класс или нет, второй <li> будет
  иметь красный цвет (если нет свойства у селектора с бо́льшей специфичностью */
li:nth-of-type(2) {
  color: red !important; /* никогда так не делайте, это лишь для примера,
                            чтобы повысить специфичность тега и переопределить
                            .list__item:nth-of-type(2n) */
}

/* 5-й <li> (или 3 .list__item) — жёлтый */
li:nth-of-type(5),
.list__item:nth-of-type(3) {
  color: yellow;
}

/* последний пункт должен быть белым (укажем это и для тега, и для класса) */
li:nth-last-of-type(1),
.list__item:last-of-type {
  color: white;
}
```
